### ISSUE TITLE
Can't import third-party library (numpy)

### ISSUE THREAD

**Issue by MrModest** [gristlabs/grist-core#1209]
### Describe the current behavior

I know that Grist natively doesn't support adding additional libraries, so I tried a workaround from this link: https://community.getgrist.com/t/install-third-party-libraries/1087

But when I just add a line `import numpy` I get the error:
```
Traceback (most recent call last):
  File "/grist/sandbox/grist/engine.py", line 985, in _recompute_one_cell
    result = col.method(record, table.user_table)
  File "usercode", line 353, in Spent
    import numpy
ImportError: No module named numpy
```
Even though I didn't turn on sandboxing. (I tried with `gvisor` and without it - the same error). 

Also, I tried to modify the [/sandbox/grist/gencode.py#L173](https://github.com/gristlabs/grist-core/blob/e95b2154051d5a8393bb005af49565d08117106a/sandbox/grist/gencode.py#L173) file as described below by the same link, but then tables stopped loading in the browser and in the docker logs a saw this error `[Sandbox] KeyError u'Projects'` (the name of the table where I tried to use the formula is 'Projects'; this part changes according to the table name where I use the import in formulas). 

### Steps to reproduce

Dockerfile:
```dockerfile
FROM gristlabs/grist:1.1.18

RUN \
  apt update && apt install -y openssl && \
  python3 -m pip install numpy
```

compose.yml
```yaml
services:
  grist:
    build: .
    container_name: grist
    cap_add:
      - SYS_PTRACE
    environment:
      GRIST_SINGLE_ORG: default-team
    ports:
      - 8484:8484
    volumes:
      # Where to store persistent data, such as documents.
      - ./volumes/grist:/persist
    restart: unless-stopped
```

### Describe the expected behavior

Import will work correctly. I can use `import numpy` in formulas.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [X] On a self-hosted instance

### Instance information (when self-hosting only)

* Grist instance:
  * Version: 1.1.18
  * Installation mode: docker
  * Architecture: ???
