### ISSUE TITLE
GitLab OIDC callback failed: RPError: JWT expired

### ISSUE THREAD

**Issue by CableGuy42069** [gristlabs/grist-core#1225]
### Describe the problem

Hi, I was using Grist for some of my personal stuff and now I wish to use it with multiple users with authentication. Since we have GitLab running and we already use it for OIDC authentication, then it is a no-brainer to use it again. But when I set it up, then I get an error when I try to login:

![image](https://github.com/user-attachments/assets/38ab364a-1c6e-491c-8f29-5fd41a7f4b6e)
![image](https://github.com/user-attachments/assets/559e235b-04d8-420f-851a-3f4e63171b6e)

> 2024-09-25 10:27:45.177 - error: OIDC callback failed: RPError: JWT expired, now 1727249265, exp 1727249237
    at Client.validateJWT (/grist/node_modules/openid-client/lib/client.js:977:15)
    at Client.validateIdToken (/grist/node_modules/openid-client/lib/client.js:766:60)
    at Client.callback (/grist/node_modules/openid-client/lib/client.js:505:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OIDCConfig.handleCallback (/grist/_build/app/server/lib/OIDCConfig.js:131:30)

Here is my docker-compose:

```yaml
services:
  grist:
    image: gristlabs/grist:1.1.18
    restart: unless-stopped
    ports:
      - '8484'
    environment:
      #Disable this after first boot
      #- GRIST_BOOT_KEY=RANDOM_SECRET_KEY
      #- DEBUG=1
      - APP_HOME_URL=https://grist.mydomain.local
      #Same email as the GitLab admin user
      - GRIST_DEFAULT_EMAIL=admin@mydomain.local
      - GRIST_OIDC_SP_HOST=https://grist.mydomain.local/oauth2/callback
      - GRIST_OIDC_IDP_ISSUER=https://gitlab.mydomain.local/.well-known/openid-configuration
      - GRIST_OIDC_IDP_CLIENT_ID="ID_FROM_GITLAB_APPLICATIONS"
      - GRIST_OIDC_IDP_CLIENT_SECRET="SECRET_FROM_GITLAB_APPLICATIONS"
      - GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT=true
      - GRIST_SINGLE_ORG=docs
      - GRIST_ORG_IN_PATH=true
      - GRIST_FORCE_LOGIN=true
      - GRIST_ANON_PLAYGROUND=false
      - GRIST_SUPPORT_ANON=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - COOKIE_MAX_AGE=none
      #- GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,multiSite,multiAccounts
    volumes:
      - persist:/persist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grist.rule=Host(`grist.mydomain.local`) || Host(`grist.mydomain.local`)"
      - "traefik.http.routers.grist.entrypoints=websecure"
      - "traefik.http.routers.grist.tls=true"
volumes:
  persist:
```

### Additional information

* Grist version:Docker Image gristlabs/grist:1.1.18
* Grist instance URL: https://grist.mydomain.local
* SSO solution used and its version (if relevant): GitLab v16.9.1-ee
* S3 storage solution and its version (if relevant):
* Docker version (if relevant): 26.1.2
* NodeJS version (if relevant):
* Redis version (if relevant):
* PostgreSQL version (if relevant):
