### ISSUE TITLE
Support standard health check endpoint

### ISSUE THREAD

**Issue by cruftex** [gristlabs/grist-core#1593]
### Describe the problem to be solved

I would like to include the application in our monitoring system.

### Describe the solution you would like

Support standard health check endpoints, e.g. like the one defined by Kubernetes, (livez and readyz)
https://kubernetes.io/docs/reference/using-api/health-checks/

Alternatively it could be exposed via the API. Here is an example:
https://admin-docs.zammad.org/en/latest/system/monitoring.html

That should not be too difficult, maybe I am able to craft a PR based on what is already there in the admin section. Thoughts?

**Comment by paulfitz** [comment]
There is a `/status` endpoint, though I'm sure it could be elaborated and brought more into alignment with applicable standards.
https://github.com/gristlabs/grist-core/blob/a8c209b7c8aebedaed740bb82a749082037c4ab6/app/server/lib/FlexServer.ts#L530-L539

**Comment by TinyServal** [comment]
You can set up something like this with the status endpoint mentioned above to do health checks in your docker compose file. Modify the query parameters if you have redis enabled.

```yml
services:
  grist:
    image: gristlabs/grist
    # rest of your config
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:8484/status?db=1",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
```
