### ISSUE TITLE
Facing errors when upgrading from version 1.16 to current version

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#1595]
### Describe the problem

Hi,
And thank you for Grist, then backbone of our everyday work. Wonderful tool and so happy it has been chosen by major European country as their alternative spreadsheet.

So, I have left our Grist version not upgraded since version 1.16. I must have faced an upgrade issue that got worse along time, hence the lagging. My bad.
Now I am trying to upgrade and get an **Error accessing document** error when I try to access any of the documents we use.
The error message when I **Reload** the document says: **openDoc call with outdated parameter.**

I also attach the docker-compose YAML file.
I am using Grist behind a SWAG instance,

Please help, and apologies for letting our installation version slip like that.
Thank you!

Stephen

### Additional information

* Grist version: 1.16
* Grist instance URL: https://grist.qtpl.net/
* SSO solution used and its version (if relevant): none
* S3 storage solution and its version (if relevant): none
* Docker version (if relevant): 28.1.1
* NodeJS version (if relevant): n/a
* Redis version (if relevant): n/a
* PostgreSQL version (if relevant): 15

Here is the docker-compose file:

```yaml
services:
  grist-kuq:
    image: gristlabs/grist:latest
    container_name: grist
    restart: unless-stopped
    volumes:
      - /home/stsinc/dkr/gsk/dta:/persist
    ports:
      - 8484:8484
    environment:
      - DEBUG=0
      - GRIST_DEFAULT_EMAIL=<obfuscated>
      - GRIST_EXPERIMENTAL_PLUGINS=true
      - GRIST_FORWARD_AUTH_LOGOUT_PATH=/signed-out
      - GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,multiSite,multiAccounts
      - GRIST_ORG_IN_PATH=false
      - GRIST_PAGE_TITLE_SUFFIX=_blank
      - GRIST_PROXY_AUTH_HEADER=Remote-Email
      - GRIST_SANDBOX_FLAVOR=unsandboxed
      - GRIST_SESSION_SECRET=<obfuscated>
      - GRIST_SINGLE_ORG=docs
      - GRIST_SUPPORT_ANON=false
      - TZ=America/New_York
      # URL and access
      - APP_DOC_URL=https://grist.qtpl.net
      - APP_HOME_URL=https://grist.qtpl.net
      - GRIST_HOST=0.0.0.0
      # Database
      - TYPEORM_DATABASE=grist
      - TYPEORM_HOST=192.168.1.66
      - TYPEORM_PASSWORD=<obfuscated>
      - TYPEORM_PORT=5432
      - TYPEORM_TYPE=postgres
      - TYPEORM_USERNAME=docker
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# For SWAG
networks:
  default:
    name: lsio
    external: true
```
