### ISSUE TITLE
After upgrade, the user is now locked on @Guest and I cannot switch to the previously created user

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#1598]
### Describe the problem

Hi All,
The upgrade issue of this morning (#1595)  was solved thanks to @paulfitz .
I could work for some time and tweaked several things using the environment variables that were created since version 1.16).

But suddenly, for a reason I cannot figure out, the only available user is `@Guest` and I have lost all the documents (or at least, they have become inaccessible -- I checked their presence in the database).

When I try to **Sign In** or **Sign Up**, I get an error: `There was an error: cannot find user`.
And yet, as I have checked in the database, the previously created users are all there.

Also, I have emptied the browser cache.

Please help,
Stephen

### Additional information

* Grist version: 1.52
* Grist instance URL: https://grist.qtpl.net/
* SSO solution used and its version (if relevant): n/a
* S3 storage solution and its version (if relevant): n/a
* Docker version (if relevant): 28.1.1 (latest)
* NodeJS version (if relevant): n/a
* Redis version (if relevant): n/a
* PostgreSQL version (if relevant): 15

Here is the `docker-compose.yml` file:

```yaml
services:
  grist-kuq:
    image: gristlabs/grist:latest
    container_name: gsk
    restart: unless-stopped
    volumes:
      - /home/stsinc/dkr/gsk/dta:/persist
    ports:
      - 8484:8484
    environment:
      - DEBUG=0
      - GRIST_EXPERIMENTAL_PLUGINS=true
      - GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,multiSite,multiAccounts,sendToDrive,tutorials,supportGrist
      - GRIST_ORG_IN_PATH=false
      - GRIST_PAGE_TITLE_SUFFIX=_blank
      - GRIST_SANDBOX_FLAVOR=pyodide
      - GRIST_SESSION_SECRET=<obfuscated>
      - GRIST_SINGLE_ORG=docs
      - GRIST_SUPPORT_ANON=false
      - GRIST_TELEMETRY_LEVEL=off
      - TZ=America/New_York
      # URL and access
      - APP_DOC_URL=https://grist.qtpl.net
      - APP_HOME_URL=https://grist.qtpl.net
      - GRIST_FORWARD_AUTH_LOGOUT_PATH=/signed-out
      - GRIST_HOST=0.0.0.0
      - GRIST_FORWARD_AUTH_HEADER=x-forwarded-user
      # Database
      - TYPEORM_DATABASE=grist
      - TYPEORM_HOST=<obfuscated>
      - TYPEORM_PASSWORD=<obfuscated>
      - TYPEORM_PORT=5432
      - TYPEORM_TYPE=postgres
      - TYPEORM_USERNAME=docker
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# For SWAG
networks:
  default:
    name: lsio
    external: true
```
