### ISSUE TITLE
which environment variables should be modified for reverse proxy

### ISSUE THREAD

**Issue by tunbk1002** [gristlabs/grist-core#212]
I read the readme and found out that there many env with `*_DOMAIN`, `*_URL`,  `*_HOST`. So... which one need to be change for a reverse proxy to work? I've tried `APP_HOME_URL`, `APP_DOC_URL` and anything I found in issues section but none of them work for me. The problem is, I can only open the site with `@Guest`, clicking login return to home. Below are my compose file
```yml
services:
  grist:
    container_name: "grist"
    image: "gristlabs/grist"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grist_router.tls=true"
      - "traefik.http.routers.grist_router.entrypoints=websecure"
      - "traefik.http.routers.grist_router.rule=Host(`grist.docker.localhost`)"
      # - "traefik.http.routers.grist_router.service=grist_service"
      # - "traefik.http.services.grist_service.loadbalancer.server.port=8484"

    environment:
      # - "GRIST_DOMAIN=0.0.0.0"
      - "APP_HOME_URL=https://grist.docker.localhost"
      - "APP_DOC_URL=https://grist.docker.localhost"
      # - "GRIST_SANDBOX_FLAVOR=gvisor"
      - "GRIST_SINGLE_ORG=docs"
      - "GRIST_ORG_IN_PATH=true"
      - "GRIST_DEFAULT_EMAIL=admin@grist.local"

    volumes:
      - "./data:/persist"

    restart: "unless-stopped"
    networks:
      - "traefik_network"

networks:
  traefik_network:
    external: true
```
