### ISSUE TITLE
Error: ActiveDoc Failed to load document

### ISSUE THREAD

**Issue by swazynski** [gristlabs/grist-core#467]
Hey, I get this error when importing a grist document:
` [NO_METADATA_ERROR: 1iXyvXGXwKXG8Dm5nG2Fvv has no metadata]`

Those are the server logs:

```
grist-grist-1          | 2023-03-23 08:21:08.327 - debug: DocManager.fetchDoc 1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.327 - debug: ActiveDoc loadDoc access=owners, userId=5, email=redacted@email.com, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.328 - debug: backupSqliteDatabase: starting copy of /persist/docs/1iXyvXGXwKXG8Dm5nG2Fvv.grist (backup) docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.330 - info: backupSqliteDatabase: copy of /persist/docs/1iXyvXGXwKXG8Dm5nG2Fvv.grist (backup) completed successfully docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.330 - debug: backupSqliteDatabase: stopped copy of /persist/docs/1iXyvXGXwKXG8Dm5nG2Fvv.grist (backup) docId=1iXyvXGXwKXG8Dm5nG2Fvv, maxStepTimeMs=1, numSteps=1
grist-grist-1          | 2023-03-23 08:21:08.331 - info: HostedStorageManager Local hash does not match redis: 857e6403c8a55dc67a2cad02777c8856 vs unknown docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.342 - info: ext doc download: 1iXyvXGXwKXG8Dm5nG2Fvv with checksum 2fd4d684b99f2c687c9fc524f6c5434e and version fbf9a47d-b965-4561-91da-9c5d53da2a4d
grist-grist-1          | 2023-03-23 08:21:08.355 - debug: DB 1iXyvXGXwKXG8Dm5nG2Fvv open successfully
grist-grist-1          | 2023-03-23 08:21:08.357 - error: ActiveDoc Failed to load document [OperationalError: SQLITE_ERROR: no such table: _grist_Tables_column] {
grist-grist-1          |   cause: [Error: SQLITE_ERROR: no such table: _grist_Tables_column] {
grist-grist-1          |     errno: 1,
grist-grist-1          |     code: 'NO_METADATA_ERROR'
grist-grist-1          |   },
grist-grist-1          |   isOperational: true,
grist-grist-1          |   errno: 1,
grist-grist-1          |   code: 'SQLITE_ERROR'
grist-grist-1          | } access=owners, userId=5, email=redacted@email.com, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.358 - debug: ActiveDoc shutdown starting access=owners, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.358 - error: ActiveDoc Failed to remove expired attachments [OperationalError: SQLITE_ERROR: no such table: _grist_Attachments] {
grist-grist-1          |   cause: [Error: SQLITE_ERROR: no such table: _grist_Attachments] {
grist-grist-1          |     errno: 1,
grist-grist-1          |     code: 'SQLITE_ERROR'
grist-grist-1          |   },
grist-grist-1          |   isOperational: true,
grist-grist-1          |   errno: 1,
grist-grist-1          |   code: 'SQLITE_ERROR'
grist-grist-1          | } access=owners, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.359 - debug: DocPluginManager.shutdown cleaning up 1 plugins
grist-grist-1          | 2023-03-23 08:21:08.359 - debug: DocPluginManager.shutdown removing tmpDir /tmp/grist-tmp-106B367uUU4oXtW
grist-grist-1          | 2023-03-23 08:21:08.359 - debug: DocStorage shutdown success
grist-grist-1          | 2023-03-23 08:21:08.360 - error: ActiveDoc failed to shutdown granular access TypeError: Cannot read property 'close' of undefined
grist-grist-1          |     at ActiveDoc.shutdown (/grist/_build/app/server/lib/ActiveDoc.js:453:40)
grist-grist-1          |     at async ActiveDoc.loadDoc (/grist/_build/app/server/lib/ActiveDoc.js:543:13)
grist-grist-1          |     at async InactivityTimer.disableUntilFinish (/grist/_build/app/common/InactivityTimer.js:76:20) access=owners, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.360 - debug: ActiveDoc shutdown complete access=owners, docId=1iXyvXGXwKXG8Dm5nG2Fvv
grist-grist-1          | 2023-03-23 08:21:08.360 - warn: Error during api call to /docs/1iXyvXGXwKXG8Dm5nG2Fvv/recover: NO_METADATA_ERROR: 1iXyvXGXwKXG8Dm5nG2Fvv has no metadata path=/docs/1iXyvXGXwKXG8Dm5nG2Fvv/recover, userId=5, altSessionId=jaNHUXoqb2AK7oJ4MD8GJv, recoveryMode=true,
grist-grist-1          | 2023-03-23 08:21:08.477 - debug: Auth[POST]: redacted.example.com /log customHostSession=, method=POST, host=redacted.example.com, path=/log, org=docs, email=redacted@email.com, userId=5, altSessionId=jaNHUXoqb2AK7oJ4MD8GJv
grist-grist-1          | 2023-03-23 08:21:08.478 - warn: client error fileName=https://redacted.example.com/v/unknown/main.bundle.js, lineNumber=2, columnNumber=404525, message=Request to https://redacted.example.com/o/docs/api/docs/1iXyvXGXwKXG8Dm5nG2Fvv/recover failed with status 500: Internal Server Error (NO_METADATA_ERROR: 1iXyvXGXwKXG8Dm5nG2Fvv has no metadata), status=500, userError=NO_METADATA_ERROR: 1iXyvXGXwKXG8Dm5nG2Fvv has no metadata, docId=1iXyvXGXwKXG8Dm5nG2Fvv, page=https://redacted.example.com/o/docs/1iXyvXGXwKXG/Untitled-document, language=de, platform=Win32, userAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0, org=docs, email=redacted@email.com, userId=5, altSessionId=jaNHUXoqb2AK7oJ4MD8GJv
```

It says it's missing the Attachments and Tables_column tables in the file, despite them being present in the grist file. The same file restores without issues on Grist Cloud.

Here is my docker compose file:
```yml
version: '3'

services:
  # Grist - Low-code database / spreadsheet platform
  grist:
    image: gristlabs/grist:latest
    # Ports: 8484
    restart: unless-stopped
    networks:
      - web
      - grist
      - db
    depends_on:
      - minio
      - db
    environment:
      - GRIST_SESSION_SECRET=${SESSION_SECRET}
      - GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,multiSite,multiAccounts
      - APP_HOME_URL=https://${GRIST_DOMAIN}
      - APP_STATIC_INCLUDE_CUSTOM_CSS=true
      - GRIST_WIDGET_LIST_URL="https://github.com/gristlabs/grist-widget/releases/download/latest/manifest.json"
      - GRIST_SANDBOX_FLAVOR=gvisor # Sandboxes individual documents so that formulas in the documents can't access data that they're not supposed to see
      - GRIST_FORCE_LOGIN=true
      # SAML
      - GRIST_SAML_IDP_LOGIN=https://${AUTHENTIK_DOMAIN}/application/saml/${AUTHENTIK_APP_SLUG}/sso/binding/redirect
      - GRIST_SAML_IDP_LOGOUT=https://${AUTHENTIK_DOMAIN}/if/session-end/${AUTHENTIK_APP_SLUG}
      - GRIST_SAML_IDP_CERTS=/config/saml/keys/signingCert.pem
      - GRIST_SAML_SP_CERT=/config/saml/keys/verificationCert.pem
      - GRIST_SAML_SP_KEY=/config/saml/keys/verificationKey.pem
      - GRIST_SAML_SP_HOST=https://${GRIST_DOMAIN}
      - GRIST_SAML_IDP_UNENCRYPTED=1 # Rely on https to encrypt
      # Snapshots
      - GRIST_DOCS_MINIO_ACCESS_KEY=grist
      - GRIST_DOCS_MINIO_SECRET_KEY=gristadmin
      - GRIST_DOCS_MINIO_USE_SSL=0
      - GRIST_DOCS_MINIO_BUCKET=grist-docs
      - GRIST_DOCS_MINIO_ENDPOINT=minio
      - GRIST_DOCS_MINIO_PORT=9000
      # Redis
      - REDIS_RUL=redis://redis
      # Home Database
      - TYPEORM_TYPE=postgres
      - TYPEORM_DATABASE=grist-home
      - TYPEORM_USERNAME=grist
      - TYPEORM_PASSWORD=grist
      - TYPEORM_HOST=db
    logging:
      options:
        max-size: 50m
    volumes:
      - ../../data/grist/grist:/persist
      - ./config/ui/ec-logo.png:/grist/static/icons/favicon.png:ro # Custom favicon
      - ./config/ui/ec-logo.png:/grist/static/icons/grist.png:ro # Custom icon
      - ./config/ui/ec-logo.svg:/grist/static/ui-icons/Logo/GristLogo.svg:ro # In-app-Logo
      - ./config/ui/ThumbPreview.svg:/grist/static/ui-icons/Logo/ThumbPreview.svg:ro # Grist file icon with custom colors
      - ./config/ui/custom.css:/grist/static/custom.css:ro
      - ./config/saml/keys:/config/saml/keys

  # Postgres for home database
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    networks:
      db:
    volumes:
      - ../../data/grist/db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    environment:
      POSTGRES_USER: grist
      POSTGRES_PASSWORD: grist
      POSTGRES_DB: grist-home

  # Minio (S3 compatible storage) for snapshots
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    networks:
      - grist
    volumes:
      - ../../data/grist/minio:/mnt/data
    environment:
      MINIO_ROOT_USER: grist
      MINIO_ROOT_PASSWORD: gristadmin
      MINIO_VOLUMES: /mnt/data
    command: server /data --address ":9000" -console-address ":9001"
    logging:
      options:
        max-size: 20m

  # Create buckets for grist
  createbuckets:
    image: minio/mc
    networks:
      - grist
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 grist gristadmin;
      /usr/bin/mc mb --ignore-existing myminio/grist-docs;
      /usr/bin/mc version enable myminio/grist-docs;
      exit 0;
      "

  # Redis for snapshots and webhooks
  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - grist
    volumes:
      - '../../data/grist/redis:/data'
    logging:
      options:
        max-size: 20m
    

networks:
  web:
    external: true
  grist:
  db:
```

Any help is greatly appreciated.
