### ISSUE TITLE
Official docker-compose file

### ISSUE THREAD

**Issue by andreapx** [gristlabs/grist-core#571]
Hi,
nice job with GetGrist. Why don't you release a docker-compose.yaml file too?

**Comment by paulfitz** [comment]
Thanks @andreapx ! There's a yaml here https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856. Do you have happen to have an example of a web app with a `docker-compose.yaml` that helped you? I see a lot of variability in how people deploy Grist, and I'm not really sure what template to give that saves work overall.

**Comment by andreapx** [comment]
@paulfitz I've tried that docker-compose removing everything related to Traefik (since I don't need a proxy), but it doesn't work since it seems to require HTTPS.
here's the docker-compse.yaml that I'm trying:

```
services:
  grist:
    image: gristlabs/grist
    environment:
      #GRIST_FORWARD_AUTH_HEADER: X-Forwarded-User
      #GRIST_FORWARD_AUTH_LOGOUT_PATH: _oauth/logout
      GRIST_SINGLE_ORG: grist  # alternatively, GRIST_ORG_IN_PATH: "true" for multi-team operation
      GRIST_DEFAULT_EMAIL: myemail
      APP_HOME_URL: https://getgrist.local
    ports:
      - "8484:8484"
    volumes:
      # You may want to put state somewhere other than /tmp :-)
      - /var/docker/getgrist/data:/persist
```
