### ISSUE TITLE
Enhancement: GraphQL endpoint

### ISSUE THREAD

**Issue by jperon** [gristlabs/grist-core#764]
As a follow-up to #757, it would be very handy, for custom plugins, to have a [GraphQL](https://graphql.org/) endpoint. This would allow, in only one query, to get all information needed, no more. But I'm not sure I realize how much work it would be, especially to deal with access rules!

**Comment by almereyda** [comment]
This will also be useful to include Grist databases into GraphQL-federation-backed data meshes.

**Comment by almereyda** [comment]
After a quick test with an adapted OpenAPI spec and little manual modifications, it is possible to hook Grist behind a GraphQL API with using Hasura Actions.

Taking https://github.com/gristlabs/grist-help/blob/master/api/grist.yml and changing it like:

```yaml
13c13
<   - url: https://{subdomain}.getgrist.com/api
---
>   - url: https://data.example.com/api
1283,1299c1283
<     WebhookProperties:
<       size:
<         type: number
<         example: 1
<       attempts:
<         type: number
<         example: 1
<       errorMessage:
<         type: string
<         nullable: true
<         example: null
<       httpStatus:
<         type: number
<         example: 200
<       status:
<         type: string
<         example: "success"
---
>     WebhookProperties: {}
1747c1731
<           enum: [Any, Text, Numeric, Int, Bool, Date, DateTime:<timezone>, Choice, ChoiceList, Ref:<tableId>, RefList:<tableId>, Attachments]
---
>           enum: [Any, Text, Numeric, Int, Bool, Date, "DateTime:<timezone>", Choice, ChoiceList, "Ref:<tableId>", "RefList:<tableId>", Attachments]
2006,2009d1989
<         dialect:
<           $ref: https://specs.frictionlessdata.io/schemas/csv-dialect.json
<         schema:
<           $ref: https://specs.frictionlessdata.io/schemas/table-schema.json
```

The additions and removals were necessary, due to the schema failing validation in the Hasura Console.

After reading up a bit on nullability in GraphQL, it became necessary to remove the `!` behind the `User` type of the `owner` property in the `Org` type at http://127.127.0.3:8080/console/actions/manage/listOrgs/modify.

After adding the Authorization token to the environment and modifying the `listOrg` action to contain an `Authorization` header from the `GRIST_TOKEN` environmental variable, it became possible to query Grist with GraphQL in the Hasura Console. It could be interesting to look into automating this procedure. Hasura has a nice export functionality, which produces a declarative description of the system.

<details><summary>Implementation</summary>
<p>

Hasura and Docker Compose `.env.example`:

```console
DATA_POSTGRES_USER=localhost-example-data
DATA_POSTGRES_PASSWORD=

META_POSTGRES_USER=localhost-example-meta
META_POSTGRES_PASSWORD=

## postgres database to store Hasura metadata
# Database URL postgresql://username:password@hostname:5432/database
HASURA_GRAPHQL_METADATA_DATABASE_URL=postgresql://${META_POSTGRES_USER}:${META_POSTGRES_PASSWORD}@hasura-meta:5432/${META_POSTGRES_USER}
## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
PG_DATABASE_URL=postgresql://${DATA_POSTGRES_USER}:${DATA_POSTGRES_PASSWORD}@data:5432/${DATA_POSTGRES_USER}
## enable the console served by server
HASURA_GRAPHQL_ENABLE_CONSOLE=true # set to "false" to disable console
## enable debugging mode. It is recommended to disable this in production
HASURA_GRAPHQL_DEV_MODE=true
HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
# HASURA_GRAPHQL_CONSOLE_ASSETS_DIR=/srv/console-assets
## uncomment next line to set an admin secret
# HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey

# For Hasura Actions to pick up their secret
GRIST_TOKEN=Bearer <token>

# For the Hasura CLI to talk to the correct endpoint
HASURA_GRAPHQL_ENDPOINT=http://127.127.0.3:8080
```

Docker Compose `compose.yml`:

```yaml
networks:
  internal:


x-default: &default
    restart: unless-stopped
    networks: ["internal"]

x-pg-default: &pg-default
    <<: *default
    image: postgres:15-alpine
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s


services:

  data:
    <<: *pg-default
    ports:
    - "127.127.0.1:5432:5432"
    volumes:
    - ./.state/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATA_POSTGRES_USER}
      POSTGRES_DB: ${DATA_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATA_POSTGRES_PASSWORD}

  hasura-meta:
    <<: *pg-default
    ports:
    - "127.127.0.2:5432:5432"
    volumes:
      - ./.state/postgres/meta:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${META_POSTGRES_USER}
      POSTGRES_DB: ${META_POSTGRES_USER}
      POSTGRES_PASSWORD: ${META_POSTGRES_PASSWORD}

  hasura-console:
    <<: *default
    image: hasura/graphql-engine
    ports:
    - "127.127.0.3:8080:8080"
    depends_on:
      hasura-meta:
        condition: service_healthy
      data:
        condition: service_healthy
    environment:
      - PG_DATABASE_URL
      - HASURA_GRAPHQL_METADATA_DATABASE_URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
      - GRIST_TOKEN
```

`justfile`:

```console
install:
  if [ ! -f .env ]; then \
    cp .env.example .env; \
    perl -pe "s/(?<=DATA_POSTGRES_PASSWORD=).*/$(openssl rand -hex 32)/" -i .env; \
    perl -pe "s/(?<=META_POSTGRES_PASSWORD=).*/$(openssl rand -hex 32)/" -i .env; \
    sed "s/<token>/${GRIST_TOKEN}/" -i .env; \
  fi
  docker compose pull

run:
  docker compose up -d

import:
  hasura metadata apply

export:
  hasura metadata export
```


With the above files and the Just task action runner, you should be able to run:

```sh
 GRIST_TOKEN=<generate on https://data.example.com/o/docs/account> just install
just run
```

It would be possible to adapt the `justfile` into a regular shell script, but that is often not what's needed.

</p>
</details>

Then you can switch to http://127.127.0.3:8080/console/ and configure your OpenAPI import and update certain types in the Actions.

Example queries that actually work:

```graphql
query Organisations {
  listOrgs {
    id
    domain
    name
    owner {
      id
      name
    }
  }
}

query WorkspaceDocuments {
  listWorkspaces(orgId: "7") {
    name
    id
    docs {
      id
      name
    }
  }
}

query LibernetesBudget {
  listTables(docId: "bPkMaixKDzP1e5zGufoE4z") {
    tables {
      id
      fields
    }
  }
}

query LibernetsColumns {
  listRecords(docId: "bPkMaixKDzP1e5zGufoE4z", tableId: "Phase_I") {
    records {
      fields
      id
    }
  }
}
```

Would be interesting to know if mutations also work.

Maybe someone would like to replicate this setup and check if it's usable for certain use cases?
