### ISSUE TITLE
Use Email not retrieved from Authentik

### ISSUE THREAD

**Issue by Hussienfahmy** [gristlabs/grist-core#878]
I set up Authentik and added a user with an email. when I sign in with that user to grist it assigns a weird name and email.

Example:
![image](https://github.com/gristlabs/grist-core/assets/65970301/0a576f3a-9260-471f-8258-c35c29ea02f4)

![image](https://github.com/gristlabs/grist-core/assets/65970301/e1b9b325-eb6b-470d-89df-cc340754a9be)

docker-compose.yml I have created.
```yml
version: '3.8'

services:
  grist:

    image: gristlabs/grist
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - GRIST_SAML_SP_HOST=http://ip:port
      - GRIST_SAML_IDP_LOGIN=http://ip:port/application/saml/grist/sso/binding/redirect/
      - GRIST_SAML_IDP_LOGOUT=http://ip:port/if/session-end/grist/
      - GRIST_SAML_IDP_CERTS=/persist/certs/private.pem
      - GRIST_SAML_IDP_UNENCRYPTED=1
      - GRIST_SAML_SP_KEY=/persist/certs/private.pem
      - GRIST_SAML_SP_CERT=/persist/certs/certificate.pem
      - GRIST_ADAPT_DOMAIN=false
      - APP_HOME_URL=http://ip:port
      - APP_DOC_URL=http://ip:port

    volumes:
      - "/home/ubuntu/grist:/persist"
```

How to make grist fetch the name and email from Authentik. since I am unable to share document access with other users?
