### ISSUE TITLE
Self Hosted docker stack won't open documents any longer

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#90]
I have been using the self-hosted stack for a full day.
Here is the `docker-compose.yml` file that worked perfectly for a full day:
```yml
version: "3"

services:
  grist:
    image: gristlabs/grist
    container_name: gst
    restart: unless-stopped
    ports:
      - "8484:8484"
    volumes:
      - /home/stsinc/dkr/kuq-gst/dta:/persist
    environment:
      - DEBUG=1
      - GRIST_SINGLE_ORG=docs
      - APP_DOC_URL=http://192.168.1.5:8484
      - APP_HOME_URL=http://192.168.1.5:8484
      - GRIST_HOST=0.0.0.0
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
```

Then, probably because I had rebuilt the stack from Portainer (but changed nothing in the `docker-compose.yml` file), Grist stopped working:

- I can still access the **home page** where all my documents are visible
- but when I try to open **any document**, I arrive on an empty page, with this error embedded in the HTML:

```html
 <script>window.gristConfig = {"homeUrl":"http://192.168.1.79:8484/","org":"docs","baseDomain":".168.1.5","singleOrg":"docs","pathOnly":true,"supportAnon":false,"pluginUrl":"plugins.invalid","timestampMs":1637534952188,"errPage":"other-error","errMessage":"no workers"};</script>
```
I then checked the data accessed by the stack in a persistent volume:
- the **documents** themselves: they are still all available (`.grist` extension)
- the **SQLite database** is valid and indeed gives access to each of the documents on disk
- besides, I haven't changed anything in the setting of the persistent volume

I then noticed in the docker log available from Portainer that Grist saw **13** documents in the persistent volume and I remembered only 10 were accessible from the free version of Grist.
I then removed the test documents from the persistent volume and deleted their records in the SQLite database.
Still does not work.

Then I noticed in the error message above that the IP address in the `baseDomain` I connect to the server from was truncated.
I tried to change it in the environment variables of the stack, but in vain.

Of course I tried to empty the cache of the 2 browsers (Firefox and Brave) I use to connect to Grist, but in vain.

PLEASE help as I am already using Grist extensively for our work here.
Thanks,
Stephen
