### ISSUE TITLE
New docker Grist image updated > all documents unreadable

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#94]
1. I have a self hosted local docker version of Grist installed on my workstation
2. Watchtower is making sure I always get the last version of docker images on the machine
3. Last night, Watchtower detected a new docker image of Grist and updated it
4. This morning none of the previously working documents is working any longer. The error is `not found: python`
5. Same with new documents

My guess is that at some point python was not included in the image.

**Comment by asitemade4u** [comment]
And when I try to import an existing document, I get this error:

![image](https://user-images.githubusercontent.com/11460106/144076406-0942eb6f-e7b8-4d6d-81a3-5e089420a204.png)

**Comment by asitemade4u** [comment]
As per our previous thread #92 I had taken care to shut down the local stack in order for it NOT to interfere with the one on the server.

**Comment by asitemade4u** [comment]
Bottom line: even if not comfortable, the situation is not too worrying to me:
- I have backups
- I have tried to reopen the saved documents using the getgrist.com website and they work perfectly.

**Comment by paulfitz** [comment]
@asitemade4u thanks for flagging this. There's already a fix in the works. We're making a series of improvements to the docker build (triggered on your previous experiences) - sorry for this glitch.

**Comment by paulfitz** [comment]
The `latest` tag has been updated. The base image we were using stopped having a default `python` command - sorry about that.

The new packaged version should become easier to configure also - it doesn't need `APP_DOC_URL` and `APP_HOME_URL`.

**Comment by asitemade4u** [comment]
Thanks Paul I will try it ASAP and let you know

**Comment by asitemade4u** [comment]
So I tried on the server with this revised `docker-compose.yml` file:
```yaml
version: "3"

services:
  grist:
    image: gristlabs/grist
    container_name: gst
    restart: unless-stopped
    ports:
      - "8484:8484"
    volumes:
      - /home/stsinc/dkr/kuq-gst/dta:/persist
    environment:
      - DEBUG=1
      - GRIST_SINGLE_ORG=docs
      - GRIST_HOST=0.0.0.0
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
```
The website is reached but I get this error:
![image](https://user-images.githubusercontent.com/11460106/144123844-277316ce-5be7-4f7c-8f81-1916fbe35de8.png)

I tried to Sign In but got the same error.

**Comment by asitemade4u** [comment]
Now for the LOCAL plain docker stack:
```yaml
version: "3"

services:
  grist:
    image: gristlabs/grist:latest
    container_name: gst
    restart: unless-stopped
    environment:
      - DEBUG=1
    ports:
      - "8484:8484"
    volumes:
      - /home/stsinc/dkr/kuq-gst/dta:/persist
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
```
This time I get this error:
![image](https://user-images.githubusercontent.com/11460106/144124285-d755958c-75e8-4acc-b5a6-cdcf7efbc383.png)

So, I try to Sign In and I get this error now: 
![image](https://user-images.githubusercontent.com/11460106/144124386-4e6c6b64-cbe4-49dd-8a05-bdbb875e152d.png)
